apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rbacsyncconfigs.rbacsync.getcruise.com
spec:
  group: rbacsync.getcruise.com
  names:
    kind: RBACSyncConfig
    plural: rbacsyncconfigs
    singular: rbacsyncconfig
    shortnames:
      - rsc
  scope: Namespaced
  version: v1alpha
  # TODO(sday): Create open API spec that validates all configs are RoleBindings
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterrbacsyncconfigs.rbacsync.getcruise.com
spec:
  group: rbacsync.getcruise.com
  names:
    kind: ClusterRBACSyncConfig
    plural: clusterrbacsyncconfigs
    singular: clusterrbacsyncconfig
    shortnames:
      - crsc
  scope: Cluster
  version: v1alpha
  # TODO(sday): Create open API spec that validates all configs are ClusterRoleBindings
